name: calendar_date_picker2
description: A lightweight and customizable calendar picker based on Flutter CalendarDatePicker, with support for single date picker, range picker and multi picker.
version: 0.5.2
homepage: https://github.com/theideasaler/calendar_date_picker2

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

screenshots:
  - description: CalendarDatePicker2 customisation demo
    path: example/screenshots/custom_range_picker_demo.png
  - description: CalendarDatePicker2 customisation demo
    path: example/screenshots/custom_range_picker_demo_2.png